font:
  size: 15

  normal:
    family: Iosevka Term SS08
    style: Regular

  bold:
    family: Iosevka Term SS08
    style: Bold

  italic:
    family: Iosevka Term SS08
    style: Italic

window:
  title: Alacritty
  decorations: none

  class:
    instance: Alacritty
    general: Alacritty

  padding:
    x: 10
    y: 10

scrolling:
  history: 32768

schemes:
  iceberg: &dark
    primary:
      background: "#161821"
      foreground: "#d2d4de"

    normal:
      black: "#161821"
      red: "#e27878"
      green: "#b4be82"
      yellow: "#e2a478"
      blue: "#84a0c6"
      magenta: "#a093c7"
      cyan: "#89b8c2"
      white: "#c6c8d1"

    # Bright colors
    bright:
      black: "#6b7089"
      red: "#e98989"
      green: "#c0ca8e"
      yellow: "#e9b189"
      blue: "#91acd1"
      magenta: "#ada0d3"
      cyan: "#95c4ce"
      white: "#d2d4de"
# colors: *dark
